---
- name: Install and configure OS X system
  hosts: localhost
  become: no
  connection: local
  gather_facts: no

  vars:
    pkg_urls:
      - url: "http://tug.org/cgi-bin/mactex-download/MacTeX.pkg"
        checksum: "sha1:d2a8383dcce32c5d4f974862492d240166fe3882"
        creates: /usr/local/texlive/2017

  tasks:
    - name: Tap casks
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - buo/cask-upgrade
        - Caskroom/cask
        - homebrew/emacs

    - name: Install casks
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - adobe-creative-cloud
        - anki
        - docker
        - firefox
        - flux
        - freedome
        - garmin-express
        - google-chrome
        - intellij-idea
        - iterm2
        - java
        - little-snitch
        - mendeley-desktop
        - micro-snitch
        - microsoft-office
        - skype
        - visual-studio-code
        - wireshark

    - name: Install brew packages
      homebrew:
        name: "{{ item }}"
      with_items:
        - ack
        - emacs
        - exercism
        - gradle
        - groovy
        - hg
        - hugo
        - mas
        - rbenv
        - ruby-build
        - scala
        - tree
        - yaml-mode

    - name: Install App Store apps
      command: "/usr/local/bin/mas install {{ item }}"
      with_items: # Find installed items with "mas list"
        - 403388562  # Transmit
        - 428846772  # Howler Timer
        - 1303222628 # Paprika Recipe Manager

    - name: Stat items installed from pkgs
      stat:
        path: "{{ item.creates }}"
      register: pkg_stat
      with_items: "{{ pkg_urls }}"

    - name: Download pkgs
      get_url:
        url: "{{ item.item.url }}"
        dest: "/private/tmp/{{ item.item.url | basename }}"
        checksum: "{{ item.item.checksum }}"
      with_items: "{{ pkg_stat.results }}"

    - name: Install pkgs
      command: "installer -pkg /private/tmp/{{ item.item.url | basename }} -target /"
      args:
        creates: "{{ item.item.creates }}"
      become: yes
      when: not item.stat.exists
      with_items: "{{ pkg_stat.results }}"
