---
- name: Install and configure OS X system
  hosts: localhost
  become: no
  connection: local
  gather_facts: no

  tasks:
    - name: Tap casks
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - buo/cask-upgrade
        - homebrew/cask
        - homebrew/emacs

    - name: Install casks
      homebrew_cask:
        name:
          - adobe-creative-cloud
          - docker
          - firefox
          - flux
          - freedome
          - garmin-express
          - google-chrome
          - intellij-idea
          - iterm2
          - java
          - little-snitch
          - mendeley-desktop
          - micro-snitch
          - microsoft-office
          - minikube
          - slack
          - skype
          - visual-studio-code

    - name: Install brew packages
      homebrew:
        name:
          - ack
          - emacs
          - gradle
          - hg
          - hugo
          - mas
          - rbenv
          - ruby-build
          - scala

    - name: Install App Store apps
      command: "/usr/local/bin/mas install {{ item }}"
      with_items: # Find installed items with "mas list"
        - 403388562   # Transmit
        - 428846772   # Howler Timer
        - 1295203466  # Microsoft Remote Desktop
        - 1303222628  # Paprika Recipe Manager
