---
- name: Install and configure OS X system
  hosts: localhost
  become: no
  connection: local
  gather_facts: no

  tasks:
    - name: Tap casks
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - Caskroom/cask
        - homebrew/emacs

    - name: Install casks
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - anki
        - docker
        - firefox
        - flux
        - freedome
        - garmin-express
        - google-chrome
        - iterm2
        - little-snitch
        - micro-snitch
        - microsoft-office
        - skype

    - name: Install brew packages
      homebrew:
        name: "{{ item }}"
      with_items:
        - emacs
        - mas
        - rbenv
        - ruby-build
        - yaml-mode

    - name: Install App Store apps
      command: "/usr/local/bin/mas install {{ item }}"
      with_items:
        - 451907568 # Paprika Recipe Manager
        - 428846772 # Howler Timer
