---
- name: Install and configure OS X system
  hosts: localhost
  become: no
  connection: local
  gather_facts: no

  tasks:
    - name: Tap casks
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - Caskroom/cask
        - homebrew/emacs

    - name: Install casks
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - adobe-creative-cloud
        - anki
        - docker
        - firefox
        - flux
        - freedome
        - garmin-express
        - google-chrome
        - intellij-idea-ce
        - iterm2
        - java
        - little-snitch
        - mendeley-desktop
        - micro-snitch
        - microsoft-office
        - skype
        - visual-studio-code
        - wireshark

    - name: Install brew packages
      homebrew:
        name: "{{ item }}"
      with_items:
        - ack
        - emacs
        - exercism
        - gradle
        - hg
        - mas
        - rbenv
        - ruby-build
        - scala
        - tree
        - yaml-mode

    - name: Install App Store apps
      command: "/usr/local/bin/mas install {{ item }}"
      with_items: # Find installed items with "mas list"
        - 403388562 # Transmit
        - 428846772 # Howler Timer
        - 451907568 # Paprika Recipe Manager
